[[biases]]
== Spatial, temporal and taxonomic biases in the data

According to the UNEP-WCMC & BIP (2020), “The post-2020 global biodiversity framework will be implemented primarily at the national level. It is therefore important that the relative roles and suitability of both global and national indicators are considered.” The provision of data suitable for the national-level implementation strategy of the post-2020 framework that addresses the challenges of scalability will require biodiversity data platforms to improve the quality and completeness of available data. As noted in a recommendation of the 3rd meeting of the CBD’s Subsidiary Body on Implementation (SBI3), addressing knowledge management for the GBF, this will involve the establishment of biodiversity observation networks and information facilities, supported by data-sharing policies, associated capacity-building and guidance, to underpin the generation of the  information needed to implement and track the goals and targets of the global biodiversity framework (CBD, 2022)

Bias refers to a systematic lack of information due to a sampling design that relies on incorrect assumptions, which may be taxonomic, geographic, temporal or environmental. One cause of bias is the lack of capacity for making existing data accessible from particular regions or across taxonomic groups. A number of initiatives have taken steps to  address these biases in global datasets. For example, GBIF´s Biodiversity Information for Development (BID) and Biodiversity Information Fund for Asia (BIFA) programmes, co-funded respectively by the European Union and the Ministry of Environment, Japan, have made significant efforts to increase capacity for mobilizing data from institutions in Africa, the Caribbean, the Pacific and Asia, and to fill data gaps in those regions. Recent guidelines on the publication of DNA-derived data through GBIF allow for the integration of data from environmental DNA sampling, and help to increase data coverage in data-poor ecosystems and taxonomic groups. And innovative uses of the data, such as the Bioclimatic Ecosystem Resilience Index (BERI) (Ferrier et al., 2020), are able to assess changes in biodiversity over time without a full time-series of observations and thus respond to temporal biases within the data.

There are also opportunities to mobilize more data, especially monitoring and inventory data at the local level. Historically, much of the biodiversity science community has been focused on the mobilization of data within established legacy collections, such as those in museums, laboratories and government agencies (Guralnick et al. 2007). There has now been a shift toward monitoring and observation projects, including citizen science. As pressure mounts to address questions about the status and trends of biodiversity at different scales, it is these data from local sources focused on the smaller-scale monitoring of national parks, waterways, and wildlands - data often collected by indigenous peoples and local communities with local knowledge - that are of critical importance in efforts to fill knowledge gaps and maintain on-going monitoring (Tengö et al. 2017, Hill et al. 2020, Brook & McLachlan 2008, Geldmann et al. 2021).

The private sector is also an important source of biodiversity data in the form of environmental assessments, impact assessments, and other project-based analyses. Increasing numbers of private sector actors are publishing biodiversity data through GBIF and the GBIF community is  engaging with the private sector directly through several initiatives, such as Data4Nature which targets public development banks to encourage data sharing as part of financing conditions . In addition, some national governments have begun to mandate private sector data publication, and financial institutions have created incentives for commercial entities to share non-sensitive data with GBIF and other national and global repositories (Equator Principles Association 2020).
