== Colophon

=== Suggested citation

Bloom D, Zermoglio P, Guralnick R, Rodrigues A, Hirsch T, Campbell J, Ali N, Ferrier S, Niamir A, Londoño MC & Sica Y (2022) Primary biodiversity data and the Post-2020 Global Biodiversity Framework. GBIF Secretariat: Copenhagen. https://doi.org/10.15468/doc-pgg2-xn60

=== Contributors

* https://orcid.org/0000-0003-1273-1807[David Bloom^], VertNet: UF/Florida Museum of Natural History 
* https://orcid.org/0000-0002-6056-5084[Paula Zermoglio^] VertNet
* https://orcid.org/0000-0001-6682-1504[Robert Guralnick^], Florida Museum of Natural History
* https://orcid.org/0000-0002-5468-2452[Andrew Rodrigues^], GBIF Secretariat
* https://orcid.org/0000-0002-5015-5807[Tim Hirsch^] GBIF Secretariat
* https://orcid.org/0000-0001-7884-2388[Simon Ferrier^] CSIRO Land and Water
* https://orcid.org/0000-0003-4511-3407[Aidin Niamir^], Senckenberg Biodiversity and Climate Research Centre
* Yanina Sica, Yale University
* https://orcid.org/0000-0003-0842-0424[Natasha Ali^], United Nations Environment Programme World Conservation Monitoring Centre (UNEP-WCMC)
* Jillian Campbell, UN Convention on Biological Diversity
* https://orcid.org/0000-0002-2317-5503[Maria Cecilia Londoño^], Humboldt Institute | Group on Earth Observations Biodiversity Observation Networks (GEO BON)


Additional contributors to subsequent versions will be credited here.

=== Licence

The document _Primary biodiversity data and the Post-2020 Global Biodiversity Framework_ is licensed under https://creativecommons.org/licenses/by-sa/4.0[Creative Commons Attribution-ShareAlike 4.0 Unported License].

=== Persistent URI

https://doi.org/10.15468/doc-pgg2-xn60

=== Document control

Adapted from Bloom DA, Zermoglio P & Guralnick R (2021) https://doi.org/10.35035/doc-2ph8-0403[Analysis of biodiversity data needs in the post-2020 framework^]. Copenhagen: GBIF Secretariat. https://doi.org/10.35035/doc-2ph8-0403.

=== Cover image

Bleeding bonnet (_Mycena sanguinolenta_), observed in Norway. Photo &copy; 2020 Kirsti Anne Mandal via https://www.gbif.org/occurrence/2848866491[Norwegian Species Observation Service].
